# Giovanni Pace wrote this code. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think 
# this stuff is worth it, you can buy me a coffee in return. 

spring.application.name=student-manager-api
server.port=8080

app.name=student-manager-api
app.version=2.0.0
app.profile=${APP_PROFILE:k8s-mysql}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/student_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:toor}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

info.app.name=${app.name}
info.app.version=${app.version}
info.app.profile=${app.profile}